### ISSUE TITLE
Automated report generation

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/beta.httparchive.org#24]
## Goal

When a crawl is complete, reports on beta.httparchive.org are immediately updated with the latest data.

## Overview

[Histogram and timeseries queries](https://github.com/HTTPArchive/beta.httparchive.org/tree/master/sql) are defined for each metric. After the crawl completes, these queries need to be rerun against the latest data and their JSON results saved to Cloud Storage (GCS). Timeseries metrics are saved in undated JSON files (eg https://cdn.httparchive.org/reports/bytesJs.json). Histograms are saved in directories corresponding to the crawl date in YYYY_MM_DD format (eg https://cdn.httparchive.org/reports/2018_02_01/bytesJs.json).

The HTTP Archive web server needs to know which dates are available for each report in GCS. It maintains [dates.json](https://github.com/HTTPArchive/beta.httparchive.org/blob/master/config/dates.json) to track all crawls for which data is available in GCS. Each date option is made available in the UI in a dropdown field to explore historical data. This JSON file is loaded into memory when the server starts up.

![image](https://user-images.githubusercontent.com/1120896/37223770-894733a4-239f-11e8-93a3-66f70e54ea69.png)

## Automation

In order to automate the report generation, we need a process that runs the queries, uploads results to GCS, and identifies which dates are available to explore in the UI.

To generate the reports automatically, we will use PubSub to signal when the data is available on BigQuery after the Dataflow pipeline has completed.

I have a few ideas for how we can use subscribers to do the actual BQ querying and backup to GCS:

1. Use a Compute Engine (GCE) server that either polls PubSub for published events or exposes an HTTP endpoint to receive a push notification. PubSub may even be overkill here since both the Dataflow job to create the BQ tables and report generation could be on the same instance.

2. Use a [Cloud Function](https://cloud.google.com/functions/) (GCF). These are lightweight and don't require provisioning servers. AFAICT these are only available in a Node.js environment and don't permit arbitrary first-party dependencies like a set of queries to run, so we'd need to side-load them through GCS or an even more convoluted node module from npm.

3. Use the existing App Engine (GAE) server to receive a push notification when the crawl is done and kick off the report generation. This is nice because the entire repository is deployed to GAE, so it can directly access the queries. I don't think we can just directly run the [generateReports.sh](https://github.com/HTTPArchive/beta.httparchive.org/blob/master/sql/generateReports.sh) shell scripts I've already written, but porting the scripts to Python should make them runnable on GAE.

The solution we go with needs to address the following issues:

- How is the report generation source code deployed?
- How will it be notified of pubsub events?
- How will it load any dependencies, like the SQL for each metric?
- How easily does it enable manual/local testing?
- How can we monitor the health of the pipeline?
- How will it put the results in GCS?
- How will the web app know the dates for which reports are available on GCS?

### Using GAE for automated report generation

I'm in favor of the third option to use GAE. I'll try to address each of the above concerns:

- Deploying the source code is trivial because the web app and generation code are developed in the same code repository and pushed to the same server. No extra deployment steps are needed.

- GAE is obviously already listening for HTTP(S) requests, so it will use the [push model](https://cloud.google.com/pubsub/docs/push) to receive notifications. During prototyping, this had some issues, like securing the endpoint. We want to ensure that only authorized users can trigger report generation.

- Loading SQL dependencies is trivial because they are included in the deployment. It will be as simple as opening a local file.

- Testing the pubsub endpoint locally should be possible using the [pubsub emulator](https://cloud.google.com/pubsub/docs/emulator), but this looks like a lot of overhead. We may want to create a "staging" GAE environment where we can deploy experimental code that is publicly accessible to receive pubsub notifications.

- We can use the existing GAE [Stackdriver logging](https://cloud.google.com/logging/) support to monitor the health of the pubsub endpoint.

- Pushing the results to GCS would be done using the [`cloudstorage` library](https://cloud.google.com/appengine/docs/standard/python/googlecloudstorageclient/read-write-to-cloud-storage) for GAE.

- The web app code already keeps a local copy of dates.json, so it could simply update this with each new crawl. There's also a case to be made that the dates could be inferred from the available directories on GCS, which is a more reliable source of truth than a JSON artifact. Although for these purposes it doesn't really matter either way.

--

So this is the proposed design to automate report generation using GAE. Please let me know if you have questions about this approach or would like to explore any of the other options.

**Comment by igrigorik** [comment]
What's the argument for not using GCE? We already kick-off the Dataflow job from the GCE instance, and it seems trivial to chain other pipeline steps behind that job right on the instance (including reusing your existing generateReports.sh logic). 

For GAE route, don't we have execution limits for HTTP calls? As in, if you have reports that need to run for some non-trivial amounts of time won't we have to figure out some background task workflow anyway. Similarly, thinking about Wappalyzer case where we need to run hundreds of queries, how would that work? Would you farm out hundreds of subrequests for each of those?

**Comment by rviscomi** [comment]
> What's the argument for not using GCE?

Not an argument against, but just different pros/cons. 

- How is the report generation source code deployed?

We would need to sync the code on GCE with GitHub. We currently do this with the [HTTPArchive/bigquery](https://github.com/HTTPArchive/bigquery) repo. We could move the report generation code from the beta repo to the bigquery repo to keep the code organized by deployment requirements. Otherwise we would be syncing two repos.

- How will it be notified of pubsub events?

It might not even have to, if it's on the same machine as the Dataflow execution. eg update the existing cron jobs to do `sync_har.sh && generateReports.sh`. Otherwise for pubsub to work we'd need a job to poll for new messages or have some HTTP endpoint listening for pushed messages.

- How will it load any dependencies, like the SQL for each metric?

These could live in the same repo as the generation script.

- How easily does it enable manual/local testing?

Local copies from git will be able to run manual testing exactly the same as the manual report generation workflow today. Alternatively, anyone can ssh into the GCE worker just like we do for Dataflow.

- How can we monitor the health of the pipeline?

GCE also enables Stackdriver logging, but not sure about their CLI interface from a shell script. We could monitor the expected outcomes, eg the expected number of JSON files were added to GCS. I think something like that is possible with GCS pubsub events.

- How will it put the results in GCS?

The generateReports.sh script already handles GCS backups.

- How will the web app know the dates for which reports are available on GCS?

The GAE point above about inferring dates from GCS directories would be handy here. Otherwise there needs to be some kind of communication system (another pubsub?) for the GCE worker to tell the GAE server to update its dates.

--

The GAE approach does require additional engineering effort for pubsub to work and to port the shell scripts to Python, so I can see GCE being easier.

--

> For GAE route, don't we have execution limits for HTTP calls?

If the limits are similar to what apply when I run the BQ jobs locally, there shouldn't be an issue, but I'm not sure.

--

We also need to keep the [CrUX reports](https://beta.httparchive.org/reports/chrome-ux-report) in mind. Besides hooking into the HTTP Archive pipeline to know when to run the queries, we also need to hook into the CrUX release to generate the corresponding HTTP Archive report. We could have a separate pubsub subscription endpoint for that or even let the CrUX project itself do the aggregation and GCS storage in the HA bucket, if it makes sense to keep them separate.

**Comment by igrigorik** [comment]
> We would need to sync the code on GCE with GitHub. We currently do this with the HTTPArchive/bigquery repo. We could move the report generation code from the beta repo to the bigquery repo to keep the code organized by deployment requirements. Otherwise we would be syncing two repos.

Git submodules is a thing too.. Not saying we need that, but an option to consider.

> It might not even have to, if it's on the same machine as the Dataflow execution. eg update the existing cron jobs to do sync_har.sh && generateReports.sh.

+1, this seems like a simple and straightforward way to do it. The reason for pubsub topic is if we had multiple subscribers, but in this case we have a single (internal) workflow.

> If the limits are similar to what apply when I run the BQ jobs locally, there shouldn't be an issue, but I'm not sure.

HTTP timeouts are typically [much more aggressive](https://cloud.google.com/appengine/articles/deadlineexceedederrors), unless we're consuming the request and spinning it off into a task queue.. which spins a worker / GCE instance, but then we're back to where we started. :-)


> We also need to keep the CrUX reports in mind. Besides hooking into the HTTP Archive pipeline to know when to run the queries, we also need to hook into the CrUX release to generate the corresponding HTTP Archive report. We could have a separate pubsub subscription endpoint for that or even let the CrUX project itself do the aggregation and GCS storage in the HA bucket, if it makes sense to keep them separate.

A simple variant of this is to do the same thing as we do for HAR pipeline.. Once a day check if the new table is available and trigger the pipeline? We know when we expect the tables to be published, and this pipeline doesn't have to depend on the HA one. 

---

I think my recommendation here is to keep things simple, if we can get away with existing scripts managing the pipeline on GCE instance — do that. WDYT?
